version: '3'
services:
        web:
                image: flask_petite_pandas
                build: .
                ports:
                        - "8777:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped